# Generated by Django 2.2.9 on 2020-01-13 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrange',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='country_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='code',
            name='agreement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administration.Agreement', verbose_name='agreement_id'),
        ),
        migrations.AlterField(
            model_name='code',
            name='alternate_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalcode',
            name='agreement',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.Agreement', verbose_name='agreement_id'),
        ),
        migrations.AlterField(
            model_name='historicalcode',
            name='alternate_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='historicalmeasureunit',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='measureunit',
            name='description',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='schema',
            name='validity_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
