# Generated by Django 2.2.9 on 2020-01-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_CambiosPrefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='validity_date',
            field=models.DateField(null=True),
        ),
    ]
