# Generated by Django 2.2.9 on 2020-01-13 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_CambiosSchema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='administration.Agreement', verbose_name='agreement_id'),
        ),
    ]
