# Generated by Django 2.2.11 on 2020-04-07 16:06 lll

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0005_CreacionCodeTypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprefix',
            name='regrouped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalprefix',
            name='regrouped_parent_prefix',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='prefix',
            name='regrouped',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='prefix',
            name='regrouped_parent_prefix',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='atccategory',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalatccategory',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='historicaltextilcategory',
            name='code',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='textilcategory',
            name='code',
            field=models.CharField(max_length=20),
        ),
    ]
