# Generated by Django 2.2.11 on 2020-04-14 22:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0006_CreacionCamposReagrupacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeType',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('code_type', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('state', models.IntegerField()),
            ],
            options={
                'verbose_name': 'CodeType',
                'verbose_name_plural': 'CodeTypes',
            },
        ),
        migrations.AlterField(
            model_name='codetypebyranges',
            name='code_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CodeType_ByRange', to='administration.CodeType'),
        ),
        migrations.AlterField(
            model_name='codetypebyranges',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='codetypebyschemas',
            name='code_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CodeType_BySchema', to='administration.CodeType'),
        ),
        migrations.AlterField(
            model_name='codetypebyschemas',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcodetypebyranges',
            name='code_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.CodeType'),
        ),
        migrations.AlterField(
            model_name='historicalcodetypebyranges',
            name='id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcodetypebyschemas',
            name='code_type',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='administration.CodeType'),
        ),
        migrations.AlterField(
            model_name='historicalcodetypebyschemas',
            name='id',
            field=models.BigIntegerField(db_index=True),
        ),
        migrations.CreateModel(
            name='HistoricalCodeType',
            fields=[
                ('id', models.BigIntegerField(db_index=True)),
                ('code_type', models.IntegerField()),
                ('description', models.CharField(max_length=500)),
                ('state', models.IntegerField()),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical CodeType',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
