# Generated by Django 2.2.11 on 2020-04-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0007_CreacionCodeTypeYRelaciones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetype',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcodetype',
            name='id',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
    ]
