# Generated by Django 2.2.11 on 2020-04-14 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0008_CambioDeIntAAutoIntCodeType'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codetypebyranges',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='codetypebyschemas',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcodetypebyranges',
            name='id',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalcodetypebyschemas',
            name='id',
            field=models.BigIntegerField(blank=True, db_index=True),
        ),
    ]
