# Generated by Django 2.2.11 on 2020-06-08 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0009_CorrecionesRelacionCodeType'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalprefix',
            name='code_quantity_consumed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprefix',
            name='code_quantity_purchased',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprefix',
            name='code_quantity_reserved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalprefix',
            name='code_residue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prefix',
            name='code_quantity_consumed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prefix',
            name='code_quantity_purchased',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prefix',
            name='code_quantity_reserved',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prefix',
            name='code_residue',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
