# Generated by Django 2.2.11 on 2020-06-08 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0010_CambiosEnPrefijos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprefix',
            name='code_quantity_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalprefix',
            name='code_quantity_purchased',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalprefix',
            name='code_quantity_reserved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historicalprefix',
            name='code_residue',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='code_quantity_consumed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='code_quantity_purchased',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='code_quantity_reserved',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='prefix',
            name='code_residue',
            field=models.IntegerField(default=0),
        ),
    ]
